[package]
name = "axum1"
version = "0.1.0"
edition = "2021"
authors = ["Peter Leeh <leeh123peter@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "A backend for recipe app"

[dependencies]
# for idiomatic error handling
anyhow = "1.0.66"
thiserror = "1.0.37"
# our choice as a web framework, and other related utilities
axum = { version = "0.6.0-rc.2", features = ["json", "headers", "multipart"] }
tokio = { version = "1.21.2", features = ["full"] }
tokio-util = { version = "0.7", features = ["io"] }
uuid = { version = "1", features = ["v4", "serde"] }
axum-extra = { version = "0.4.0-rc.1", features = ["cookie", "cookie-signed", "form"] }
tower-http = { version = "=0.3.4", features = ["add-extension", "trace", "cors", "fs"] }
# for handling dates
chrono = { version = "0.4.22", features = ["serde"] }
time = { version = "0.3.16", features = ["formatting", "serde", "serde-well-known"] }
# for configuration and auxiliary things
config = "0.13.2"
dotenv = "0.15.0"
rand = "0.8.5"
# (de)serialization
serde = { version = "1.0.147", features = ["derive"] }
# database interaction
sqlx = { version = "0.6.2", features = ["runtime-tokio-rustls", "any", "postgres", "json", "macros", "chrono", "uuid", "migrate", "offline", "bigdecimal"], default-features = false }
# tracing and logging utilites
sentry = "0.28.0"
sentry-tracing = "0.27"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
log = "0.4.14"
# monitoring
metrics-exporter-prometheus = "0.11.0"
axum-prometheus = { git = "https://github.com/Ptrskay3/axum-prometheus", branch = "axum-0.6" }
# password hashing
argon2 = { version = "0.4", features = ["std"] }
# for avoiding exposing sensitive information
secrecy = { version = "0.8.0", features = ["serde"] } 
# session ext
tower = "0.4.13"
futures = "0.3"
async-session = "3.0.0"
async-redis-session = { path = "./crates/async-redis-session" }
# emails
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"] }
# searching
meilisearch-sdk = "0.20"
serde_json = "1.0.87"
# OAuth
oauth2 = "4.2.3"
# Input validation
validator = { version = "0.16", features = ["derive"] }
# regex (mostly for validation) and utilities
regex = "1.6.0"
once_cell = "1.16.0"
axum-macros = "0.3.0-rc.1"
base64 = "*"
blake3 = "*"
paste = "1.0.9"
async-stream = "0.3.3"

[dev-dependencies]
